[package]
name = "devicetree"
version = "0.0.1"
authors = ["Chris Williams <diodesign@tuta.io>"]
edition = "2018"

[dependencies.hashbrown]
version = "0.7.2"
features = [ "nightly" ]

[dependencies.byterider]
path = "../byterider"

[dependencies.qemuprint]
path = "../qemuprint"