[package]
name = "devicetree"
version = "0.0.1"
authors = ["Chris Williams <chrisw@diosix.org>"]
edition = "2018"

[dependencies.hashbrown]
version = "0.11.2"
features = [ "nightly" ]

[dependencies.byterider]
path = "../byterider"
